In [12]:
import numpy as np

In [11]:
np.random.randn(2, 3)

array([[ 0.38871663, -0.04126386,  0.29588432],
       [-0.42527999,  1.72763912, -0.86835257]])

In [4]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

In [3]:
A.sum() # ça fait la somme du tableau A

27

In [4]:
A.sum(axis=0) # ça fait la somme des elemests de chaque colone du tableau A. axis=0 donne la position verticale

array([ 8,  7, 12])

In [5]:
A.sum(axis=1) # ça fait la somme des elemests de chaque ligne du tableau A. axis=1 donne la position horiontale

array([ 8, 19])

In [6]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27], dtype=int32)

In [7]:
A.prod()

0

In [9]:
A.min()

0

In [10]:
A.max()

9

In [15]:
A.min(axis=0)

array([3, 0, 3])

In [12]:
A.sum(axis=0)

array([ 8,  7, 12])

In [17]:
A.argmin(axis=0) #les indexes (positions) des plus petit

array([1, 0, 0], dtype=int64)

In [18]:
A.sort()

In [19]:
# Statistics
A.mean() # la moyenne de A

4.5

In [20]:
A.var() # la variance de A

8.583333333333334

In [21]:
A.std() # L'ecartype

2.9297326385411577

In [23]:
np.corrcoef(A) 

array([[1.        , 0.99717646],
       [0.99717646, 1.        ]])

In [26]:
valuers, counts = np.unique(A, return_counts=True)

In [28]:
counts

array([1, 2, 1, 1, 1], dtype=int64)

In [32]:
valuers[counts.argsort()]

array([0, 5, 7, 9, 3])