In [1]:
import numpy as np

In [ ]:
"""
Pour créer un tableau d’une seule dimension, il suffit de faire appel à la fonction array().
    Remarque :
Le principe de dimension est simple. Pour un tableau d’une seule dimension on a une liste, 
pour deux dimensions on a une liste de listes, pour trois dimensions on a une liste de listes de listes. 
Pour n dimensions on a une liste de n-1 listes imbriquées.
"""

In [2]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [3]:
A.shape # la forme du tableau (n lignes, m colonnes)

(3,)

In [4]:
A.ndim # c'est le nombre de dimention du tableau

1

In [5]:
A.size # la taille du tableau ou le nombre d'element du tableau

3

In [6]:
B = np.zeros((3, 2)) # initialiser un tableau de 3 lignes et 2 colonnes ou une matrice contenant que des zéros.
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
B.shape

(3, 2)

In [8]:
B.ndim

2

In [10]:
C = np.ones((3, 4)) #initialiser un tableau de 3 lignes et 2 colonnes ou une matrice ne contenant que des « 1 ».
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
D = np.full((2, 4), 2) # qui remplie un tableau ou une matrice d'une seule valeur
D

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [11]:
np.random.seed(0) # Pour garder les memes nombres aleatoires apres reexecution
np.random.randn(3, 2) # Initialiser un tableau avec des nombres aleatoires univariée de moyenne 0 et de variance 1

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788]])

In [19]:
# Pour avoir la matrice d’identité, c’est-à-dire une matrice dont tous les éléments sont des zéros sauf pour la diagonale 
# qui contient des uns, on fait appel à la fonction eye(n).
# Cette fonction renvoie un tableau carré de deux dimensions de taille n.

np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Constructeur: linspace est un constructeur qui nous permet de creer un tableau à une dimention en précisant 
#  le début, la fin et le nombre d'element du tableau
np.linspace(0, 10, 20) 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
# Constructeur: arange est un constructeur qui nous permet de creer un tableau à une dimention en précisant 
#  le début, la fin et le pas entre les elements du tableau
np.arange(0, 10, 2) 

array([0, 2, 4, 6, 8])

In [35]:
M = np.ones([3, 2])
M.ravel()

array([1., 1., 1., 1., 1., 1.])

In [28]:
L = np.zeros([3, 2])
L

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
N = np.hstack((L, M))
print(N)
N.shape

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


(3, 4)

In [36]:
np.vstack((M, L))


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
def initialisation(m, n):
    W = np.random.randn(m, n)
    W = np.concatenate((W, np.ones((W.shape[0], 1))), axis = 1)
    return W

In [40]:
initialisation(3, 4)

array([[ 0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  1.        ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  1.        ],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826,  1.        ]])